version: '3.8'
services:
  shopManagement:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: shopAdmin
      POSTGRES_PASSWORD: abcd1234
      POSTGRES_DB: shop_management